name: "Report Bug"
description: "Pls REPORT ANY BUGS YOU SEE IN RYZEN ITSELF"

labels: "bug"
title: "Report Bug"

body:
    
    - type: markdown
      attributes:
          value: |
               Hi @user95401, here is a bug in Ryzen!
    
    - type: textarea
      id: what-happened
      attributes:
        label: What happened?
        description: Also tell us, what did you expect to happen?
        placeholder: Tell us what you see!
        value: "A bug happened! But i am will not sent any helpful info :)"
      validations:
        required: true
