name: "Report Bug"
description: "Pls REPORT ANY BUGS YOU SEE IN RYZEN ITSELF"

labels: "bug"
title: "Report Bug"

body:
    
    - type: markdown
      attributes:
          value: |
               Hi @user95401, here is a bug in Ryzen:
          
    - type: textarea
